# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5434
    environment:
      POSTGRES_USER: pythonistas
      POSTGRES_PASSWORD: monmotdepassepythonclassmatesdb1.
      PGDATA: /var/lib/pgsql/data
    volumes:
      - postgres:/data/postgres

volumes:
    postgres:
